title: CafeSec Lab
author: CafeSec Lab Research Team
email: contact@cafeseclab.com
description: Independent research notes on internet cafe and gaming venue security
url: "https://magnoormeno-dot.github.io"
baseurl: "/netcafe-security-lab"
theme: minima
future: true
plugins:
  - jekyll-feed
  - jekyll-sitemap

minima:
  skin: auto

header_pages:
  - about.md

feed:
  path: feed.xml
