#requires -Version 5.1
<#
.SYNOPSIS
  Seam #5: render an Invoke-RuleValidation report into the CVP evidence format
  (docs/cvp/lab-validation-evidence.md). Closes the loop lab -> docs/cvp.
.DESCRIPTION
  Reads a rule-validation report (the .jsonl produced by Invoke-RuleValidation.ps1) and emits a
  fixed-format Markdown evidence file. The output is REPRODUCIBLE SYNTHETIC LAB EVIDENCE, never
  field validation -- it states only that the repository's detection rules convert/compile cleanly
  (and, when run in a live lab, fire on controlled benign telemetry). Per the repo data policy a
  human must review the file before it is cited in the CVP evidence pack.

  Use -Stub to generate a placeholder before any validation has been run.
.PARAMETER ReportPath
  Path to a rule-validation .jsonl report. Default: newest reports/rule-validation-*.jsonl in the module.
.PARAMETER OutputPath
  Output Markdown path. Default: <repo>/docs/cvp/lab-validation-evidence.md.
.PARAMETER Stub
  Emit a placeholder (no report required), to be regenerated once the lab runs the validation.
.EXAMPLE
  .\Export-CvpEvidence.ps1 -Stub        # create the placeholder committed to docs/cvp
.EXAMPLE
  .\Invoke-RuleValidation.ps1 ; .\Export-CvpEvidence.ps1   # generate from the newest report
.NOTES
  No admin required. Output is English to match docs/cvp; written as UTF-8 (no BOM), LF.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$ReportPath,
    [string]$OutputPath,
    [switch]$Stub
)
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\..\lib\Common.ps1"

$moduleRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)   # 04-validation-lab\
$repoRoot   = Split-Path -Parent $moduleRoot
if (-not $OutputPath) { $OutputPath = Join-Path $repoRoot 'docs\cvp\lab-validation-evidence.md' }

# Locate the newest report unless one was given or we are stubbing.
if (-not $Stub -and -not $ReportPath) {
    $reportDir = Join-Path $moduleRoot 'reports'
    $latest = Get-ChildItem -Path $reportDir -Filter 'rule-validation-*.jsonl' -ErrorAction SilentlyContinue |
        Sort-Object Name -Descending | Select-Object -First 1
    if ($latest) { $ReportPath = $latest.FullName }
    else {
        Write-Warn2 "未找到 rule-validation 报告;改为生成 stub。先跑 Invoke-RuleValidation.ps1 再重试以填充真实结果。"
        $Stub = $true
    }
}

# Parse the report (jsonl: one {kind,rule,ok,detail} per line).
$rows = @()
if (-not $Stub) {
    foreach ($line in (Get-Content -LiteralPath $ReportPath)) {
        $t = $line.Trim()
        if ($t) { $rows += ($t | ConvertFrom-Json) }
    }
}

function Get-Count { param($Kind, $Ok) @($rows | Where-Object { $_.kind -eq $Kind -and [bool]$_.ok -eq $Ok }).Count }

# Run metadata.
$utc = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss \U\T\C')
$commit = 'unknown'; $branch = 'unknown'
if (Get-Command git -ErrorAction SilentlyContinue) {
    try {
        Push-Location $repoRoot
        $commit = (& git rev-parse --short HEAD 2>$null)
        $branch = (& git rev-parse --abbrev-ref HEAD 2>$null)
    } catch { $commit = 'unknown' } finally { Pop-Location }
}
$runtime = "Windows PowerShell $($PSVersionTable.PSVersion) on $([System.Environment]::OSVersion.VersionString)"
$reportName = if ($ReportPath) { Split-Path $ReportPath -Leaf } else { '(pending — run Invoke-RuleValidation.ps1)' }

$sigmaPass = Get-Count 'sigma' $true;  $sigmaFail = Get-Count 'sigma' $false
$yaraPass  = Get-Count 'yara'  $true;  $yaraFail  = Get-Count 'yara'  $false
$pending = '(pending)'

# Build Markdown.
$md = New-Object System.Collections.Generic.List[string]
$md.Add('# Lab Validation Evidence (synthetic, reproducible)')
$md.Add('')
$md.Add('> **This is reproducible synthetic lab evidence, not field validation.** It records only that')
$md.Add('> the repository''s detection rules in `01-hardening-checklist/detection/` convert/compile cleanly')
$md.Add('> and (when run in a live, isolated lab) fire on controlled benign telemetry. Per the data policy in')
$md.Add('> [`docs/cvp/evidence-pack.md`](evidence-pack.md), a human must review this before it is cited as')
$md.Add('> evidence. Generated by `04-validation-lab/scripts/analysis/Export-CvpEvidence.ps1`.')
$md.Add('')
$md.Add('## Run metadata')
$md.Add('')
$md.Add('| Field | Value |')
$md.Add('| --- | --- |')
$md.Add("| Generated | $utc |")
$md.Add("| Source report | $reportName |")
$md.Add("| Repo commit | $commit ($branch) |")
$md.Add("| Runtime | $runtime |")
$md.Add('| Rule source | `01-hardening-checklist/detection/` |')
$md.Add('')
$md.Add('## Summary')
$md.Add('')
$md.Add('| Category | Passed | Failed |')
$md.Add('| --- | --- | --- |')
if ($Stub) {
    $md.Add("| Sigma -> opensearch convert | $pending | $pending |")
    $md.Add("| YARA compile | $pending | $pending |")
} else {
    $md.Add("| Sigma -> opensearch convert | $sigmaPass | $sigmaFail |")
    $md.Add("| YARA compile | $yaraPass | $yaraFail |")
}
$md.Add('')
$md.Add('## Per-rule results')
$md.Add('')
$md.Add('| Kind | Rule | Result | Detail |')
$md.Add('| --- | --- | --- | --- |')
if ($Stub) {
    $md.Add('| _pending_ | _run Invoke-RuleValidation.ps1_ | — | — |')
} else {
    foreach ($r in $rows) {
        $res = if ([bool]$r.ok) { 'PASS' } else { 'FAIL' }
        $detail = ([string]$r.detail) -replace '\|', '\|'
        $md.Add("| $($r.kind) | $($r.rule) | $res | $detail |")
    }
}
$md.Add('')
$md.Add('## Reproduce')
$md.Add('')
$md.Add('```powershell')
$md.Add('cd 04-validation-lab\scripts\analysis')
$md.Add('.\Setup-RuleEngines.ps1        # one-time, during the temporary-connectivity phase')
$md.Add('.\Invoke-RuleValidation.ps1    # validate 01-hardening-checklist/detection rules')
$md.Add('.\Export-CvpEvidence.ps1       # regenerate this evidence file')
$md.Add('```')
$md.Add('')
$md.Add('Live-fire validation (rule fires on controlled benign telemetry) is performed in a running,')
$md.Add('network-isolated lab; see [`04-validation-lab/COVERAGE.md`](../../04-validation-lab/COVERAGE.md).')
$md.Add('')
$md.Add('## Reviewer gate (before citing in the CVP evidence pack)')
$md.Add('')
$md.Add('- [ ] Repo commit above matches the release/branch being cited.')
$md.Add('- [ ] Pass/fail counts match the linked `reports/rule-validation-*.jsonl` artifact.')
$md.Add('- [ ] Wording stays "synthetic / reproducible", never "field-validated".')
$md.Add('- [ ] No host-specific paths or sensitive data leaked into the table details.')
$md.Add('')

$text = ($md -join "`n") + "`n"
$outDir = Split-Path -Parent $OutputPath
if ($outDir -and -not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
if ($PSCmdlet.ShouldProcess($OutputPath, 'write CVP evidence')) {
    [System.IO.File]::WriteAllText($OutputPath, $text, (New-Object System.Text.UTF8Encoding($false)))
    $mode = if ($Stub) { 'STUB' } else { "from $reportName" }
    Write-Ok "已生成 CVP 证据 ($mode): $OutputPath"
    if ($Stub) { Write-Host "跑 Invoke-RuleValidation.ps1 后重跑本脚本即可用真实结果填充。" -ForegroundColor Gray }
}
